In [24]:
!pip install tqdm


You should consider upgrading via the '/anaconda/envs/py38_default/bin/python -m pip install --upgrade pip' command.


In [25]:
import os
import pathlib
trainingImagesDir = '../public/assets/data/training/asl_alphabet_train'
trainingImagesOutputDir = '../public/assets/data/training/asl_alphabet_train_grey'

pathlib.Path(trainingImagesOutputDir).mkdir(parents=True, exist_ok=True)

trainingSigns = sorted(os.listdir(trainingImagesDir))

In [12]:
import cv2
import tensorflow as tf
import mediapipe as mp
import numpy as np
from tqdm import tqdm
import pathlib

mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

def process_sign(sign):
    IMAGE_FILES = os.listdir(os.path.join(trainingImagesDir, './', sign))
    grey_out_dir = os.path.join(trainingImagesOutputDir, './', sign)
    pathlib.Path(grey_out_dir).mkdir(parents=True, exist_ok=True)
    print("Processing " + sign)
    for idx, fileName in enumerate(IMAGE_FILES):
        # Read an image, flip it around y-axis for correct handedness output (see
        # above).
        file = os.path.join(trainingImagesDir, './', sign, fileName)
        image = cv2.imread(file)
        # Convert the BGR image to RGB before processing.
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        outfile = os.path.join(grey_out_dir, fileName)
#         print(outfile)
#         print(outfile)
        cv2.imwrite(outfile, gray)

process_sign("A")
# for sign in trainingSigns:
#     process_sign(sign)

    #     for sign in trainingSigns:
    #         process_sign(sign)
    #         sign_idx = sign_idx + 1
    #         pbar.update(1)

Processing A


In [26]:
import cv2
import tensorflow as tf
import mediapipe as mp
import numpy as np
from tqdm import tqdm
import os

mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

tensors=[]
count = 0
# vidcap = cv2.VideoCapture('output_crf17.mkv')
# success,image = vidcap.read()

# with mp_hands.Hands(
#     static_image_mode=True,
#     max_num_hands=2,
#     min_detection_confidence=0.5) as hands:
#     while success:
#         success,image = vidcap.read()
        
#         if success:
#             # Convert the BGR image to RGB before processing.
#             results = hands.process(image)

#             if not results.multi_hand_landmarks:
#                 continue

#             for hand_landmarks in results.multi_hand_landmarks:
#                 index = 0
#                 tensor = np.array([[res.x, res.y, res.z] for res in hand_landmarks.landmark]).flatten()
#                 tensors.append(tf.linalg.normalize(tf.constant(tensor)))

#             count += 1
#     print (count)

with mp_hands.Hands(
    static_image_mode=True,
    max_num_hands=2,
    min_detection_confidence=0.5) as hands:
    sign = 'A'
    IMAGE_FILES = os.listdir(os.path.join(trainingImagesOutputDir, './A'))
    for idx, fileName in enumerate(IMAGE_FILES):
        # Read an image, flip it around y-axis for correct handedness output (see
        # above).
        file = os.path.join(trainingImagesDir, './', sign, fileName)
        image = cv2.flip(cv2.imread(file), 1)
        # Convert the BGR image to RGB before processing.
        out = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        results = hands.process(out)

        if not results.multi_hand_landmarks:
            continue
        
        print (results.multi_hand_landmarks)
        break

        for hand_landmarks in results.multi_hand_landmarks:
            index = 0
            tensor = np.array([[res.x, res.y, res.z] for res in hand_landmarks.landmark]).flatten()
            tensors.append(tf.linalg.normalize(tf.constant(tensor)))

        count += 1
    print (count)


[landmark {
  x: 0.551543653011322
  y: 0.5552890300750732
  z: -8.413272780671832e-07
}
landmark {
  x: 0.46153995394706726
  y: 0.5192225575447083
  z: -0.013066370971500874
}
landmark {
  x: 0.400984525680542
  y: 0.45549237728118896
  z: -0.021430889144539833
}
landmark {
  x: 0.3873842656612396
  y: 0.39300134778022766
  z: -0.03420479968190193
}
landmark {
  x: 0.3905313014984131
  y: 0.34014731645584106
  z: -0.04334723949432373
}
landmark {
  x: 0.45082783699035645
  y: 0.3822767734527588
  z: 0.0074765561148524284
}
landmark {
  x: 0.4364841878414154
  y: 0.33187755942344666
  z: -0.026555348187685013
}
landmark {
  x: 0.4445531666278839
  y: 0.3802356719970703
  z: -0.049095090478658676
}
landmark {
  x: 0.4541296064853668
  y: 0.4280320703983307
  z: -0.05729285255074501
}
landmark {
  x: 0.5019063353538513
  y: 0.3806082308292389
  z: -0.0018953294493258
}
landmark {
  x: 0.4882024824619293
  y: 0.3315187692642212
  z: -0.037810713052749634
}
landmark {
  x: 0.4962783455848

In [3]:
import cv2
import tensorflow as tf
import mediapipe as mp
import numpy as np
from tqdm import tqdm
import pathlib

tensor = tf.constant(np.array([[0.0, 2.0, 5.0], [1.0, 5.0, 5.0]]))
print(tensor)
print(tf.linalg.normalize(
    tensor, ord=np.inf, axis=None, name=None
))
# print()

tf.Tensor(
[[-1.  2.  5.]
 [ 1.  5.  5.]], shape=(2, 3), dtype=float64)
(<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[-0.2,  0.4,  1. ],
       [ 0.2,  1. ,  1. ]])>, <tf.Tensor: shape=(1, 1), dtype=float64, numpy=array([[5.]])>)


In [3]:
np.full(2, 12)

array([12, 12])